# Pre-commit hook configuration
# Install: uv tool install pre-commit && pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Gitleaks - Secret scanning
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
        name: Gitleaks - Detect hardcoded secrets
        description: Scan for secrets using Gitleaks
        entry: gitleaks protect --verbose --redact --staged
        language: golang
        pass_filenames: false

  # Local hooks (custom scripts in this repo)
  - repo: local
    hooks:
      - id: check-version-bump
        name: Check VERSION bump for runtime changes
        entry: bash -c 'PRE_COMMIT=1 scripts/check-version-bump.sh'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        verbose: true
